### ISSUE TITLE
Delegated zones are incompatible with the ownership processor

### ISSUE THREAD

**Issue by JamesHarrison** [octodns/octodns#1012]
Hi,

I've had a poke at this but couldn't come up with an obvious neat technical fix so I thought I'd better open an issue to discuss. It's perhaps a bit of a niche case, but delegation of sub-zones fairly often happens for administrative reasons.

In the following case:

```
zone.tld
delegate.zone.tld
```

Where both zones are configured separately:

```yaml
zones:

 zone.tld.:
    processors:
      - ownership
    sources:
      - config
    targets:
      - route53

  delegate.zone.tld.:
    processors:
      - ownership
    sources:
      - netbox
      - config
    targets:
      - route53
```

And in the `zone.tld` yaml, a NS record delegating `delegate.zone.tld` exists, OctoDNS will refuse to add the ownership record for the NS entry, thus aborting the plan:
```
File "/Users/james.harrison/dev/octodns/octodns/zone.py", line 95, in add_record
    raise SubzoneRecordException(
octodns.zone.SubzoneRecordException: Record _owner.ns.delegate.zone.tld. is under a managed subzone
```

The ownership record here is valid - though some providers like Cloudflare may reject it - it just won't be authoritative, but that's irrelevant for ownership records. The NS record is required to effect the delegation.

The fix paths I can see would be to either have the records marked by the ownership processor skipped over by the checks in Zone#add_record, or for ownership to create records in a way that avoids creating records under the delegate (e.g. a _owned_recordname_delegate_ txt record in the top-level zone), but I'm not sure either of these work particularly well.
