### ISSUE TITLE
octodns-dump doesn't output weighted records

### ISSUE THREAD

**Issue by jmreicha** [octodns/octodns#1022]
Apologies if this has already been explained/addressed. It looks like the `octodns-dump` command does not create weighted records for route53 entries.

Here is the record in AWS console.

<img width="1291" alt="image" src="https://github.com/octodns/octodns/assets/1039098/d2cc0de4-7a24-4dcf-9ecc-d52e4055834c">

Here's the generated yaml:

```yaml
---
? ''
: ttl: 172800
  type: NS
  values:
  - ns-1524.awsdns-62.org.
  - ns-1573.awsdns-04.co.uk.
  - ns-434.awsdns-54.com.
  - ns-678.awsdns-20.net.
login:
  ttl: 300
  type: A
  value: 35.164.80.159
```

Here's the command I used:

```bash
octodns-dump --lenient --config-file=config/base.yaml --output-dir=/tmp/ test-settings-here.com. route53
```

Is there some other way to handle this that I have missed?

**Comment by ross** [comment]
It's come up a time or two previously. Looks like https://github.com/octodns/octodns/issues/788#issuecomment-934493661 has a good response that I won't fully duplicate here, but TL;DR is that there are ~infinite possibilities in the details across all the providers and octoDNS doesn't attempt to support them all. Instead it has an opinionated view that can for the most part work the same across them all.

**Comment by jmreicha** [comment]
Understood. Is there any interest in supporting this type of behavior on a provider by provider basis? I use weighting in route53 often enough, I wonder if it would be useful to add?

**Comment by ross** [comment]
Weighted serving is supported, there's just not automatic way to dump arbitrarily configured stuff to one. It's basically done with a `dynamic` record with a single pool with the values and a single (default) rule that points to it. The base values should have the same IPs in it sans weight. If you don't wish to have health checking you can set the `status: up` on the values and it should behave essentially the same as a "simple" weighted record. Details in https://github.com/octodns/octodns/blob/main/docs/dynamic_records.md

**Comment by jmreicha** [comment]
Here's what I came up with. Is that in the ballpark?

```yaml
login:
  dynamic:
    pools:
      test:
        values:
          - status: up
            value: '35.164.80.159'
            weight: 20
          - status: up
            value: '66.209.83.107'
            weight: 80
    rules:
      - pool: test
  ttl: 300
  type: A
  values:
    - 66.209.83.107
    - 35.164.80.159
```
