### ISSUE TITLE
Support for "all" zones of a provider in config file

### ISSUE THREAD

**Issue by shalinmakadia** [octodns/octodns#1025]
Allow same action on all zones in a provider. For instance, if there are 12 zones in PowerDNS and we want to sync them to cloudflare then we can simply use keyword "all" (like in DNScontrol's get-zones command, or any other convenient keyword) instead of listing all 12 zones in the config file.

This allows to perform desired actions on all the zones in one provider without having to list them all. In addition, it saves effort to edit config file everytime there is a zone added/removed on the provider.

Example config below:

```
---
providers:
  powerdns:
    class: octodns_powerdns.PowerDnsProvider
    host: 1.2.3.4
    port: 12345
    api_key: powerdns_secret_api_key
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    token: cloudflare_secret_api_token

zones:
  all:
    sources:
      - powerdns
    targets:
      - cloudflare
```
