### ISSUE TITLE
octoDNS v1.0.0 does not apply octodns:exclude

### ISSUE THREAD

**Issue by brianeclow** [octodns/octodns#1036]
Morning!

I noticed during an initial testing of octoDNS v1.0.0 it was throwing some errors on previously working zone data. It is throwing the exception for types not supported by all providers servicing a given zone.

```yaml
providers:
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
  nsone:
    class: octodns_ns1.Ns1Provider
  route53:
    class: octodns_route53.Route53Provider
  splitprimary:
    class: octodns.provider.yaml.SplitYamlProvider
    directory: ./data/primary
zones:
  example.com.:
    contents: Primary Split Zone
    sources:
    - splitprimary
    targets:
    - cloudflare
    - nsone
    - route53
```

```yaml
refer:
- octodns:
    excluded:
      - route53
    lenient: true
  type: ALIAS
  value: example.service.io.com.
- type: TXT
  value: v=spf1 include:spf.example.com -all
```

It throws the error:
```txt
octodns.provider.SupportsException: route53: ALIAS records not supported for refer.example.com.
```

I also noticed, the exclusions are not additive, they appear to be replacing the previously excluded entry. Example, we have another excluded entry/type which is also appearing to throw the error inconsistently/interchangeably. This appears to be related to some internal ordering within python's data object as the data is loaded, and the tooling only responds with a single error message.

**Comment by ross** [comment]
😦, hrm. No recent changes related to that area are immediately coming to mind. Do you have a previous version where you know it was working to help narrow things down.

The bit that excludes things happens during Zone.changes which hasn't changed for 6 years.

https://github.com/octodns/octodns/blob/ca52349111e5dc66043a6a9205f72ab38d43ded2/octodns/zone.py#L193-L200

Perhaps something has changed further up the stack from that. 

For this case I believe changes is called here where self is the target.

https://github.com/octodns/octodns/blob/ca52349111e5dc66043a6a9205f72ab38d43ded2/octodns/provider/base.py#L247

Will try and carve out some time this afternoon to see if I can reproduce the issue.

**Comment by brianeclow** [comment]
> Do you have a previous version where you know it was working to help narrow things down.

Name: octodns
Version: 0.9.21

The Route53 provider has remained
Name: octodns-route53
Version: 0.0.5

For octoDNS v1.0.0, I bumped the octodns-ns1 provider from v0.0.4 to v0.0.5. I also included a bump for the most recent boto and boto-core, which usually doesn't effect anything. Just confirmed, even with removing those additional bumps, the error still occurs.

**Comment by ross** [comment]
With the current `main`, 1 PR ahead of 1.0.0, I created a 2 YamlProvider setup, `config`, and `out`:

```yaml
providers:

  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config

  out:
    class: octodns.provider.yaml.YamlProvider
    directory: /tmp/octodns

zones:
  exxampled.com.:
    sources:
      - config
    targets:
      - out
```

And then a single entry in the zone file:

```yaml
refer:
- octodns:
    excluded:
      - out
    lenient: true
  type: ALIAS
  value: example.service.io.com.
- type: TXT
  value: v=spf1 include:spf.example.com -all
```

When run as above I get the following output with only 1 of the 2 refer records:

```console
********************************************************************************
* exxampled.com.
********************************************************************************
* out (YamlProvider)
*   Create Zone<exxampled.com.>
*   Create <TxtRecord TXT 3600, refer.exxampled.com., ['v=spf1 include:spf.example.com -all']> (config)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing Records=0
********************************************************************************
```

If I change the excludes to out2 (which won't match) I get the following with both:

```console
********************************************************************************
* exxampled.com.
********************************************************************************
* out (YamlProvider)
*   Create Zone<exxampled.com.>
*   Create <AliasRecord ALIAS 3600, refer.exxampled.com., example.service.io.com.> (config)
*   Create <TxtRecord TXT 3600, refer.exxampled.com., ['v=spf1 include:spf.example.com -all']> (config)
*   Summary: Creates=2, Updates=0, Deletes=0, Existing Records=0
********************************************************************************
```

There is a warning message in both cases about `ALIAS` not being allowed type for non-root records.

```console
2023-08-07T12:28:17  [4683034112] WARNING Record Invalid record "refer.exxampled.com.", ./config/exxampled.com.yaml, line 21, column 3
  - non-root ALIAS not allowed
```

If I add a `route53` provider and include it in the targets list by default I get an exception with:

```console
octodns.provider.SupportsException: route53: ALIAS records not supported for refer.exxampled.com.
```

If I then add `strict_supports=false` for `route53` I get the following plan with only the TXT

```console
...
2023-08-07T12:31:14  [4464016896] WARNING Route53Provider[route53] ALIAS records not supported for refer.exxampled.com.; omitting record
...
********************************************************************************
* exxampled.com.
********************************************************************************
* route53 (Route53Provider)
*   Create Zone<exxampled.com.>
*   Create <TxtRecord TXT 3600, refer.exxampled.com., ['v=spf1 include:spf.example.com -all']> (config)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing Records=0
********************************************************************************
```

If I add `route53` to the ALIAS's excluded list I get the same plan, but the warning message about omitting the record goes away.
