### ISSUE TITLE
A hybrid YAML+SplitYAML provider

### ISSUE THREAD

**Issue by viranch** [octodns/octodns#1040]
We have a use-case for mixing flat-yaml files and split-yaml files for various zones:

```
config
├── foo.com.yaml
└── bar.net.
    ├── $bar.net.yaml
    └── www.yaml
```

For this to work, we have to have 2 different config providers:

```
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
  config_split:
    class: octodns.provider.yaml.SplitYamlProvider
    directory: ./config

zones:
  foo.com.:
    sources:
      - config
    targets: [..]
  bar.net.:
    sources:
      - config_split
    targets: [..]
```

It'd be nice to instead be able to use a single "hybrid" provider:

```
providers:
  config:
    class: octodns.provider.yaml.HybridYamlProvider
    directory: ./config

zones:
  foo.com.: &zone
    sources:
      - config
    targets: [..]
  bar.net.: *zone
```

And this would become even more powerful with https://github.com/octodns/octodns/pull/1026!
