### ISSUE TITLE
Avoid duplicate strings from YAML as *.domain.com.domain.com ?

### ISSUE THREAD

**Issue by lbrachet** [octodns/octodns#1080]
Hello,

I'm using the v0.9 and I'm going to upgrade to the latest v1.2.1.

I'm often doing the same error in adding the domain at the end of the subdomain so the PLAN / APPLY do "repo.domain.com.domain.com" to Route53:

```
from file: 
path/domain.com.yaml
```

```
# added ".domain.com"
repo.domain.com:
  ttl: 300
  type: CNAME
  value: id.jfrog.io.
```

```
# result from Route53:
repo.domain.com.domain.com
```

```
# solution: I MUST NOT ADD ".domain.com" and just let:
repo:
  ttl: 300
  type: CNAME
  value: id.jfrog.io.
```

I'm wondering if I can't use a Processor https://github.com/octodns/octodns#processors to do it but maybe it could be added directly to the "validate" workflow?

Thanks!

**Comment by ross** [comment]
> I'm wondering if I can't use a Processor https://github.com/octodns/octodns#processors to do it but maybe it could be added directly to the "validate" workflow?

I kind of seems like a validation, but that'd be a little annoying if there are situations where someone actually meant to double up like that. I guess they could always put `lenient` on the record. Anyone else have thoughts on this?

**Comment by lbrachet** [comment]
Yes, with the `lenient: true` we could imagine that the double is allowed.

From my case, every time we doubled, it was a mistake. ;)

**Comment by ross** [comment]
Slept on this and as of this morning I'm leaning towards a `Processor` being a better path since it's more of a oppsie thing than a spec compliance or best practice sort of thing (as is the case with the existing validations.)

It should also be more flexible and allow users to specify what is and isn't allowed. Will throw something together and link it up once pushed.

**Comment by ross** [comment]
Have a look at https://github.com/octodns/octodns/pull/1083. When used it'd likely make sense to add it as:

```yaml
manager:
    processors:
        - zone-name

processors:

    zone-name:
        ...
```
