### ISSUE TITLE
Cloudflare TTL 'auto' differences

### ISSUE THREAD

**Issue by KRoss45** [octodns/octodns#1090]
Issue is an assumption of what's going on.

We've been using 0.9.11 forever and have started testing 1.x.    Last round of tests was with 1.2.1.  

What is seen in testing on a single domain is the TTL is flagged for update.  eg:
```
*   Update
*     <ARecord A 300, activeactive.lavexproducts.com., ['192.168.55.22', '10.20.55.22']> ->
*     <ARecord A 1, activeactive.lavexproducts.com., ['192.168.55.22', '10.20.55.22']> (config)
```

In Cloudflare, the above A record is set to Auto, where `1` is what you set in the config.  
Config:
```
activeactive:
  octodns:
    cloudflare:
      proxied: true
  ttl: 1
  type: A
  values:
    - 192.168.55.22
    - 10.20.55.22
```

The output snip from above is another dry run after applying the updates already; so octodns wants to re-apply the same change despite having just done it.

Running with 
`octodns-cloudflare       0.0.3`
