### ISSUE TITLE
octodns manager removes `octodns-meta` records on upgrade

### ISSUE THREAD

**Issue by fjaeckel** [octodns/octodns#1110]
During upgrades from 0.9.21 to 1.3.0 octodns drops all `octodns-meta` records with `include_meta: True` set.

This happens for NS1, Route53 and PowerDNS providers - others have not been tested.

The log shows that its correctly added to the `global_post_processors` with the right attributes.
```
2023-11-28T00:42:28  [139947483277120] INFO  Manager __init__: adding meta to processors and providers, appending it to global_post_processors list
2023-11-28T00:42:28  [139947483277120] INFO  MetaSource[meta] __init__: record_name=octodns-meta, include_time=False, include_uuid=False, include_version=False, include_provider=True, ttl=60
```

running octodns shows that the TXT record is being "emptied", not deleted - however this results in them being deleted for all providers involved. I do not know why the provider was set twice prior to this, there was no manual configuration in place for this:
```
 * intauth-fra (PowerDnsProvider)
 *   Update
 *     <TxtRecord TXT 60, octodns-meta.github.net., ['provider=intauth-fra', 'provider=intauth-fra']> ->
 *     <TxtRecord TXT 60, octodns-meta.github.net., ['']> ()
 *   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=27
```

The log also shows:
```
2023-11-28T00:46:39  [139947306624768] WARNING Record Invalid record "octodns-meta.github.net."
 - missing value(s)
 ```

which then leads to above changes.

For the above to happen I just had in my config:

```
---
manager:
    include_meta: True
```

However I can reproduce the same result with:
```
---
manager:
  include_meta: False
  max_workers: 8
  post_processors:
    - meta

processors:
  meta:
    class: octodns.processor.meta.MetaProcessor
    record_name: meta
    include_provider: true
    include_time: false
```

The moment I switch `include_time: true` all records appear, but the `provider=` tag is missing from the TXT record.

I can make it work with the following, but its a little cumbersome for our configuration:
```
---
manager:
  include_meta: False

processors:
  meta:
    class: octodns.processor.meta.MetaProcessor
    record_name: octodns-meta
    include_provider: true
    include_time: false

zones:
  foobar.com:
    sources:
      - super_source
    processors:
      - meta
    targets:
      - route53
 ```

So my hunch is thats its related to the `global_post_processors`, it definitely does not matter which `record_name` I choose.
