### ISSUE TITLE
YAML Provider doesn't record default TTL

### ISSUE THREAD

**Issue by squintfox** [octodns/octodns#1144]
I'm not sure if this is a bug, a feature request or as designed, but the YAML output file of the YAML Provider doesn't record what the default TTL was when the file was created.  Therefore, this code causes any records using the default TTL value to skip writing it to the file.

https://github.com/octodns/octodns/blob/3acfd174b61ff5352294a0fbb5f9fb706d76bf14/octodns/provider/yaml.py#L387-L389

What you wind up with is a file that doesn't have all the data you need to restore/migrate it.  I know that it's generally going to be the default 3600, but there's simply no way to know for sure.  I'm not sure what reasoning may be behind the design, but it seems to be either every record should have it's value written to the file or the default should be there so it can be re-hydrated somehow.

I searched the issues and found a related mention, but it seemed to treat this behavior as accepted fact and didn't question it.

**Comment by ross** [comment]
It's working as designed. It avoids including a TTL on records that match the default to avoid the noise of explicitly listing it out on every one of them. The default TTL is 1 hour:

https://github.com/octodns/octodns/blob/3acfd174b61ff5352294a0fbb5f9fb706d76bf14/octodns/provider/yaml.py#L30-L32

So any records with that value will omit the TTL field. So long as the config provider uses the same default then everything will match the dumped source.

You can use a configured provider rather than an auto created one by passing `--output-provider` to the `octodns-dump` invocation:

```
$ octodns-dump --config-file=config.yaml --output-provider config --output-dir /tmp/octodns somedomain.com. daprovider
```

That will let you use a specific `YamlProvider` with the config you specify. With that you can change the default to another "real" value or put something unique in there so that nothing will match it and every record will have a `ttl` entry. e.g.


```yaml
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config/
    # invalid ttl here will force the `ttl` field when used for dumps and 
    # require that a valid ttl one be specified on every single record.
    default_ttl: -1
```
