### ISSUE TITLE
Config values set using environment variables are casted to a float

### ISSUE THREAD

**Issue by wjgauthier** [octodns/octodns#1148]
After upgrading to OctoDNS version 1.5.0, I started getting syncing errors with the PowerDNS provider. I get an error like this when I run octodns-sync:
`urllib3.exceptions.LocationParseError: Failed to parse: http://127.0.0.1:10000.0/api/v1/servers/localhost/zones/example.com`

I set the value of the PowerDNS provider options using environment variables like this: 
```
providers:
  powerdns:
    api_key: env/POWERDNS_API_KEY
    class: octodns_powerdns.PowerDnsProvider
    host: env/POWERDNS_HOST
    port: env/POWERDNS_PORT
    scheme: env/POWERDNS_SCHEME
```

Based on the error message above, it appears that the port is converted to a float. The breaking change was introduced in commit 4c09f4b, where the value is casted to a float. Changing this to an int fixes the problem.

https://github.com/octodns/octodns/blob/3acfd174b61ff5352294a0fbb5f9fb706d76bf14/octodns/manager.py#L393
