### ISSUE TITLE
provider/source tags or aliases

### ISSUE THREAD

**Issue by joewilliams** [octodns/octodns#119]
It would be nice to be able to group sources and providers together and use that combined "alias" as the source or target for a zone. This would simplify configuration of zones and as you add sources or providers they would get updated automatically as long as they had the right tags.

```
  internal-master:
    class: github.provider.github_powerdns.GitHubPowerDnsProvider
    tags: ['internal']
  external_provider_1:
    class: octodns.provider.dyn.DynProvider
    tags: ['external', 'dyn']
  external_provider_1:
    class: octodns.provider.route53.Route53Provider
    tags: ['external', 'aws']
  external_provider_3:
    class: octodns.provider.route53.Route53Provider
    tags: ['external', 'aws']

zones:
  blah.io.:
    sources:
      - config
    targets:
      - external # alias for external_provider_1, external_provider_2 and external_provider_3

  internaldomain.com.:
    sources:
      - config
    targets:
      - internal # alias for internal-master

  externalaws.io.:
    sources:
      - config
    targets:
      - aws # alias for external_provider_2 and external_provider_3

```
