### ISSUE TITLE
SRV records cannot not be IPs

### ISSUE THREAD

**Issue by nogweii** [octodns/octodns#1192]
I think it's technically valid but doesn't work. Figure attempting to parse the record (minus the trailing dot) with the [ipaddress](https://docs.python.org/3/library/ipaddress.html) module is probably a good check to see if an IP was passed in.

This comes from me adding a Minecraft SRV record and not realizing I had to add another DNS record: :sweat_smile: 

```yaml
_minecraft._tcp.mc:
  - type: SRV
    value:
      weight: 0
      priority: 5
      port: 25565
      target: 1.2.3.4.
```
