### ISSUE TITLE
V2: Remove SplitYamlProvider in favor of YamlProvider with the appropriate config values

### ISSUE THREAD

**Issue by ross** [octodns/octodns#1216]
```yaml
       config:
         class: octodns.provider.yaml.YamlProvider
         # extension is configured as split_extension
         split_extension: .
         split_catchall: true
         disable_zonefile: true
```
