### ISSUE TITLE
Feature request: comments on individual records

### ISSUE THREAD

**Issue by robertn4-d** [octodns/octodns#1225]
First, thank you for making octodns. It's great!

I would like to request a feature where you can add comments or a description on individual records. In a collaborative environment, where multiple users can create and modify records, having the ability to add comments would be super useful. It could provide context for why a particular record was created or clarify who is responsible for it. While Git history can offer some insights, having a dedicated comment would enhance clarity and make it easier for users to understand the rationale behind a record

**Comment by ross** [comment]
The YAML format allows comments that can accomplish what you're after. We used them quite extensively for more complex/indirect pieces of GitHub's setup and I use them in my personal setup as well:

```yaml
# This is our main web address
www.exxampled.com:
  type: A
  value: 1.2.3.4
```

**Comment by zajdee** [comment]
When a YAML file is loaded using `PyYAML`, and then dumped to a file using PyYAML again (e.g. because of CI/CD linting, automatic reformatting, ...), the comments beginning with `#` are lost.
As an alternative, this is how I have added comments in the past. I would also appreciate if this was officially supported.
```
server:
- comments:
  - 192.0.2.1 - ldap02a
  - 192.0.2.2 - ldap02b
  type: A
  values:
  - 192.0.2.1
  - 192.0.2.2
- comments:
  - 2001:db8:dead::beef - ldap02a
  - 2001:db8:dead::babe - ldap02b
  type: AAAA
  values:
  - 2001:db8:dead::beef
  - 2001:db8:dead::babe
client:
- comment: 203.0.113.1 - client01
  type: A
  value: 203.0.113.1
- comment: 2001:db8:ca11::1 - client01
  type: AAAA
  value: 2001:db8:ca11::1
```

**Comment by ross** [comment]
The `YamlProvider` could add support for a provider specific key under the `octodns` top-level key to allow that. Tbh it likely already preserves them, I can't remember off-hand.

```yaml
something:
  octodns:
    yaml-coment: this might be preserved
  type: TXT
  value: Hello World!
```
