### ISSUE TITLE
Order of record values (especially TXT Record)

### ISSUE THREAD

**Issue by ayyurtduzen** [octodns/octodns#1227]
Hi, thank you for developing OctoDNS! :)

I am happy to use it to create hosted zones and records in AWS Route53.
I would like to learn how I can create the records with the values in the exact order written in yaml file.

For example, I am writing my configuration like this:
```
mail:
  ttl: 300
  type: TXT
  values:
  - zz
  - yy
  - bb
  - aa
  ```

However, I see the record values in AWS Route53 console in alphabetical order like:
```
"aa"
"bb"
"yy"
"zz"
```

Using the flag `enforce_order: false` is just helping to preserve the order of records but not values. I am writing my config.yaml in case I use it in the wrong way:
```
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones
    default_ttl: 300
    enforce_order: false
  route53:
    class: octodns_route53.Route53Provider
    
zones:
  testzone.com.:
    sources:
      - config
    targets:
      - route53
```
I really would like to learn how to do this. I tried to write a custom plugin but I couldn't find the method to overwrite. Thank you for helping.

**Comment by ross** [comment]
Record values are sorted by https://github.com/octodns/octodns/blob/53a310ec518feef14f49f47ccc3d0d3bea16c975/octodns/record/base.py#L326 and there's currently no way to disable that functionality. 

This is done in order to provide consistent behavior throughout octoDNS and across providers. I believe order isn't supposed to matter to things querying DNS records as they're intended to treat each value independently so it shouldn't impact the behavior of anything. Do you have a use case where it's causing problems or is it more of an aesthetic thing?

> Using the flag `enforce_order: false` is just helping to preserve the order of records but not values. I am writing my config.yaml in case I use it in the wrong way:

This just applies to the order of records in the file and keys in the record data. It has no impact on the values.

**Comment by ayyurtduzen** [comment]
Thank you for the response!

It actually has an impact. Changing the order will invalidate this DKIM key, thus failing mail signing.
If I create the TXT record in AWS console, and dump octodns configuration, it shows sorted version but this doesn't affect the existing record (this is good). However, if I want to create a new TXT record via octodns, then it creates values as sorted.

Can you give me any hint of how I can overwrite this line (or method itself) `self.values = sorted(self._value_type.process(values))` while using [octodns_route53 ](https://github.com/octodns/octodns-route53) provider?

**Comment by ross** [comment]
Can your share the record you've having problems with. You can swap the name and value details with a placeholder, but I'm trying to make sure I understand what's going on and make sure we're o the same page.

For reference this is roughly what I'd expect the record to look like:

```yaml
google._domainkey:
    type: TXT
    value: v=1; a=rsa-sha256; d=example.com; s=big-email; h=from:to:subject; bh=uMixy0BsCqhbru4fqPZQdeZY5Pq865sNAnOAxNgUS0s=; b=LiIvJeRyqMo0gngiCygwpiKphJjYezb5kXBKCNj8DqRVcCk7obK6OUg4o+EufEbBtRYQfQhgIkx5m70IqA6dP+DBZUcsJyS9C+vm2xRK7qyHi2hUFpYS5pkeiNVoQk/Wk4wZG4tu/g+OA49mS7VX+64FXr79MPwOMRRmJ3lNwJU=
```

**Comment by ayyurtduzen** [comment]
Thank you, it seems Octodns is handling the values which has more than 255 characters automatically (for TXT records). So, rather than separating them into different values, I am writing as one value. It solved my problem, thank you.

Now, I am trying to find a solution for the semicolon issue. I am writing my config as below (by using octodns-route53 provider)
```
dummy_one:
  ttl: 300
  type: TXT
  value: v=DKIM1;t=s;p=MIICIjANBg
```
it gives me `unescaped ; in "v=DKIM1;t=s;p=MIICIjANBg"` error.

Secondly, if I write this:
```
dummy_two:
  ttl: 300
  type: TXT
  value: v=DKIM1\;t=s\;p=MIICIjANBg
```
It creates `v=DKIM1\;t=s\;p=MIICIjANBg` in AWS console.

However, all I want is `v=DKIM1;t=s;p=MIICIjANBg`
I checked old issues, but I couldn't understand the proper solution for route53.
