### ISSUE TITLE
BUG: Tag and comment implementation does not seem right

### ISSUE THREAD

**Issue by derekmpage** [octodns/octodns#1250]
Tags and Comments can be added at the answer level.
Here is how it looks in the Cloudflare UI

![Image](https://github.com/user-attachments/assets/7d22368b-8a77-44f4-84d2-7c0459e459c7)
![Image](https://github.com/user-attachments/assets/eb317ca7-d234-4ac7-8bf2-795649abb04a)

When running an octodns-dump of the zone to config Yaml we see this...

```
---
? ''
: - type: A
    values:
    - 151.101.1.xx
    - 151.101.129.xx

... 

bob:
  octodns:
    cloudflare:
      auto-ttl: true
      comment: dpage-comment2
      tags:
      - othertag2
      - tag2
  ttl: 300
  type: A
  values:
  - 151.101.193.xx
  - 151.101.65.xx
~                     
```

```
Here we see context for  `octodns.cloudflare:` comments and tags are referenced in the yaml config at the nodes record level.
So the tags and comments are lost for records that have more then one answer value.

Here we see there is no metadata for answer 151.101.65.xx value. (tag1)


Now when we sync this config back up to cloudflare....

********************************************************************************
* xxx.xx.
********************************************************************************
* config (YamlProvider)
*   Create <ARecord A 300, bob.xxx.xx., ['151.101.193.xx', '151.101.65.xx'], {'cloudflare': {'auto-ttl': True, 'comment': 'comment1', 'tags': ['tag1']}}> (cloudflare)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing=4, Meta=False
********************************************************************************


2025-05-20T12:02:07  [140650804848448] INFO  YamlProvider[config] apply: making 1 changes to xxx.xx.
2025-05-20T12:02:07  [140650804848448] INFO  Manager sync:   1 total changes
```

Then after a dump again.... I see Things have changed to ( tag1 )....

```
 dpage@MA-dpage  ~/git/ops-octodns   OPS-73119/feature-helper-scripts ±  cat zones/kay.ac.yaml
---
? ''
: - type: A
    values:
    - 151.101.1.xx
    - 151.101.129.xx
...

bob:
  octodns:
    cloudflare:
      auto-ttl: true
      comment: comment1
      tags:
      - tag1
  ttl: 300
  type: A
  values:
  - 151.101.193.xx
  - 151.101.65.xx
```

The really strange thing is the UI did not get over written, which I don't quite understand yet.

![Image](https://github.com/user-attachments/assets/5ebabef1-c20e-4b31-934f-1be6a64df78b)
