### ISSUE TITLE
Badly formated SRV records are considered valid

### ISSUE THREAD

**Issue by jleroy** [octodns/octodns#1257]
I was trying to create an SRV record but used an incorrect syntax in the YAML file:

```yaml
_autodiscover._tcp:
  - port: 443
    priority: 0
    target: autodiscover.example.com.
    type: SRV
    weight: 1
```

...instead of: 

```yaml
_autodiscover._tcp:
  - type: SRV
    value:
      port: 443
      priority: 0
      target: autodiscover.example.com.
      weight: 1
```

...which resulted in an empty value:

```sh
$ octodns-sync --config-file=production.yaml
[...]
2025-06-10T07:42:39  [8450055936] INFO  Plan
********************************************************************************
* example.com.
********************************************************************************
* config_yaml_tmp (YamlProvider)
*   Create <SrvRecord SRV 1800, _autodiscover._tcp.example.com., ['']> (config_example)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing=22, Meta=False
********************************************************************************
```

Generated YAML target:

```yaml
---
_autodiscover._tcp:
  type: SRV
  values: []
```
