### ISSUE TITLE
Get current zone name as a variable in YAML files

### ISSUE THREAD

**Issue by jleroy** [octodns/octodns#1258]
I'm working to deploy DKIM records across a number of domains. I'm using a dedicated provider in conjunction with `shared_filename` and `disable_zonefile` to add the records in questions only to the zones that need them:

```yaml
providers:
  ...
  fastmail:
    class: octodns.provider.yaml.YamlProvider
    directory: ./snippets/Fastmail
    shared_filename: Fastmail.yaml
    disable_zonefile: true
  ...

zones:
  ...
  example.com.:
    sources:
      - fastmail
      - config_example
    targets:
      - bunny
    ...
```

But the DKIM records themselves are handled by our provider, who asks to add the following CNAME records to each zone:

```yaml
fm1:
  type: CNAME
  value: fm1.[domain.tld].dkim.fmhosted.com.

fm2:
  type: CNAME
  value: fm2.[domain.tld].dkim.fmhosted.com.

fm3:
  type: CNAME
  value: fm3.[domain.tld].dkim.fmhosted.com.
```

How can I set the zone name dynamically in the YAML file?
A solution can be to have something like a "$zone_name" variable who will be replaced by YAMLProvider when reading records names / values?
