### ISSUE TITLE
User Specific Configuration Limits/Restrictions

### ISSUE THREAD

**Issue by yzguy** [octodns/octodns#181]
Not sure the "user specific" part of it is right, however I'll explain so maybe it's clear

So this was a thought out of me doing some work with our DNS zones around TTLs. It had really become the wild west, and there was a large range of TTLs (5 secs to 24 hours).

I was wondering if a new feature might be a configuration section where you can specify things like:

* Minimum TTL
* Maximum TTL
* Valid Regions (GeoDNS)
* Etc.

This might tie into #75, where we specify extra configurations like default TTL.

I'm mostly thinking about the TTL use case. If I try to run noop or doit, it will error saying it is less than or greater than Min/Max TTL, and if I dump it will error during the dump, and if you say lenient it will dump it with the current value, but again, you hit the error applying.

Wondering if there is a place for something like that.

```
---
config:
  default_ttl: 3600
  min_ttl: 300
  max_ttl: 86400

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
```

**Comment by ross** [comment]
I like the idea. We have some internal validation scripts that are run as part of CI. Not all of them would fit into this sort of model, but I could see this being useful. 

Not 100% sure what it'd look like, but I'd be tempted to steer towards something dynamic/configurable similar to the PlanOutputs support. There could be built in options like TttlValidator and it'd allow people to develop and add arbitrary validations of their own. For the above the config with a custom validator it might look like:

```yaml
validations:
   custom-stuff:
    class: foo.validations.BarValidator
  ttl:
    class: octodns.validations.TtlValidator
    default_ttl: 3600
    min_ttl: 300
    max_ttl: 86400
```
