### ISSUE TITLE
Can't find doc about SafePlan

### ISSUE THREAD

**Issue by o-be-one** [octodns/octodns#187]
Hello guys,

i've seen that OctoDNS includes a "SafePlan" to prevent too much updates. I haven't seen any documentation regarding this feature setting. It's an interesting point and i think that the main documentation should describe fields like this, it will be definitively useful :).

Have a good week!

**Comment by ross** [comment]
There's two optional parameters on the `BaseProvider` which makes them available to app providers 

https://github.com/github/octodns/blob/de4dc76b3f17ab41a2cc562439584d834e4c4c5e/octodns/provider/base.py#L16-L17

They can be configured with something like:

```yaml
    foo:
        class: foo.bar.Provider
        update_pcent_threshold: 0.5
        delete_pcent_threshold: 0.5        
```

The defaults are on the Plan object

https://github.com/github/octodns/blob/de4dc76b3f17ab41a2cc562439584d834e4c4c5e/octodns/provider/plan.py#L20-L21

Would welcome a PR getting that into something starting on documenting providers in the `docs/` dir 😁
