### ISSUE TITLE
Handle multiple zones with the same name.

### ISSUE THREAD

**Issue by f33rx** [octodns/octodns#260]
Have this situation where I have multiple zone names that are the same, only the last element is returned.

**Comment by yzguy** [comment]
Is this in the case of a zone that is a Public Hosted Zone and Private Hosted Zone as well? I had been wondering about this case.

**Comment by f33rx** [comment]
@yzguy It is! In this case, it's a public and two private zones. (!!) The intent was to persist a zone config to disk and then use the `backup` to load other providers.

**Comment by ross** [comment]
My first thought would be to break things up into separate configs, e.g.

```
config/
  external/
    zone1.com.yaml
  external.yaml
  internal/
    zone1.com.yaml
  internal.yaml
``` 

Things would then be synced with two seperate runs, one with `--config-file config/external.yaml` and another with `--config-file config/internal.yaml`. Each would point the YamlProvider to matching directory. 

Something like that make sense/work or there more nuance to what you're trying to do?

**Comment by brianeclow** [comment]
If I am understanding your suggestion, then for a split config/data setup like mine. The files would be like:

```
config/
   internal.yaml
   external.yaml
   simple.yaml
data/
   internal/
      zone1.com.yaml
   exteranl/
      zone1.com.yaml
   zone2.com.yaml
```

With the `data` keys for `internal` and `external` having the values `./data/internal` and `./data/external` respectively. Then  for `simple` config, the `data` key have the value `./data`

Correct?

**Comment by f33rx** [comment]
`https://github.com/github/octodns/blob/6da23ea7956298c53bb9985a35d0a30fac6cd9a8/octodns/provider/route53.py#L283` Seems to use the name field to find the ID. If I ask route53 for all the things called `domain.com` and I get three things. It seems to choose the last thing it got from the api. I tried to add an optional field for specifying an array of `zone id`'s but failed spectacularly.

**Comment by ross** [comment]
> If I am understanding your suggestion, then for a split config/data setup like mine.

Not quite sure what `simple.yaml` would be for/meaning here. Maybe i'd be better to think of things as two completely different octoDNS setups/configs, one for internal and one for external that know nothing about each other. 

## internal 

### `config/internal.yaml`

```yaml
---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./data/internal/

  powerdns:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 1.2.3.4
    api_key: env/POWERDNS_API_KEY_EXT 

zones:

  some-zone.com.:
    sources:
      - config
    targets:
      - powerdns
```

### `data/internal/some-zone.com.yaml`

```yaml
---
'':
  type: ALIAS
  value: internal-target.foo.com.
```

## external

### `config/external.yaml`

```yaml
---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./data/external/

  route53:
    class: octodns.provider.route53.Route53Provider
    access_key_id: env/AWS_ACCESS_KEY_ID
    secret_access_key: env/AWS_SECRET_ACCESS_KEY

zones:

  some-zone.com.:
    sources:
      - config
    targets:
      - route53
```

### `data/external/some-zone.com.yaml`

```yaml
---
'':
  type: ALIAS
  value: external-target.foo.com.
```

That's about the simplest setup that I can come up with. It's definitely possible to do mor involved/complicated things like sharing some records in a `data/base/some-zone.com.yaml` and using multiple `YamlProvider`s, but it's probably best to ignore that until the above stuff is super clear/understood as that could take a bit of thinking to grok. Best not to read this part unless you really need it :grin:

### `config/internal.yaml`

```yaml
---
providers:
  base:
    class: octodns.provider.yaml.YamlProvider
    directory: ./data/base/

  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./data/internal/

  powerdns:
    class: octodns.provider.powerdns.PowerDnsProvider
    host: 1.2.3.4
    api_key: env/POWERDNS_API_KEY_EXT 

zones:

  some-zone.com.:
    sources:
      - base
      - config
    targets:
      - powerdns
```

External would basically look the same and just point the `config` provider at the `external` directory.

You'd then have `data/(base|internal|external)/some-zone.com.yaml` files. Base would have records that appear both internally and externally and then internal would have the inside only stuff and external would have the outside only bits. 

There's super cool/powerful things that can be done with multiple sources (and targets.) We use this extensively to fill out zones with both static and dynamic records, sometimes multiple dynamic sources.

> Seems to use the name field to find the ID. If I ask route53 for all the things called domain.com and I get three things. It seems to choose the last thing it got from the api. I tried to add an optional field for specifying an array of zone id's but failed spectacularly.

Yeah the providers definitely don't support multiple zones with the same name. I don't think any of the systems I know off off-hand would support the idea other than Route53 (and maybe Google Cloud.) For Route53 specifically they'd need to be using separate accounts/creds. I don't think multiple zones with the same name in the same account/provider will be a supported concept in general.
