### ISSUE TITLE
YAML syntax doesn't validate in any online YAML parsers

### ISSUE THREAD

**Issue by thockin** [octodns/octodns#266]
I ran `octodns-dump`.  It successfully pulled data.  Looking at the YAML it dumped, I can't get it to validate in other YAML parsers.

```
---
? ''
: - ttl: 300
    type: A
    value: 1.2.3.4
  - ttl: 300
    type: MX
    values:
    - exchange: example.com.
  - ttl: 300
    type: TXT
    values:
    - hello=world
```

As I understand the syntax, the `? ''` declares a Key of "" and the subsequent line is the value.  Changing it to:

```
---
'':
 - ttl: 300
    type: A
    value: 1.2.3.4
  - ttl: 300
    type: MX
    values:
    - exchange: example.com.
  - ttl: 300
    type: TXT
    values:
    - hello=world
```

Seems to pass obvious parsers.  Is this a bug?  Intentional?  Why is it obfuscated when it doesn't seem to be necessary?

@dims
