### ISSUE TITLE
!include in YAML

### ISSUE THREAD

**Issue by hmoffatt** [octodns/octodns#412]
Would it be possible to be able to !include another YAML file within a zone? This would make it easy to have a set of common records included in multiple zones.

There are PyYAML add-on libraries to take care of this for you like https://pypi.org/project/pyyaml-include/

**Comment by ross** [comment]
You can likely accomplish that by using multiple `YamlProvider` `sources`, or any combination of sources really. They'll be processed in the order specified so the first one will add its records to the zone and then the second will add on top of that.

e.g.

```yaml

providers:
  base:
    class: octodns.provider.yaml.YamlProvider
    directory: config/base
  specific:
    class: octodns.provider.yaml.YamlProvider
    directory: config/specific

...

zones:
  myzone.com.:
    sources:
      - base
      - specific
...
```

If you specifically want to use that library you can likely create a custom provider that inherits from `YamlProvider` and overrides `_populate_from_file` https://github.com/github/octodns/blob/master/octodns/provider/yaml.py#L50.
