### ISSUE TITLE
Octodns-sync support sync without override the dynamic records

### ISSUE THREAD

**Issue by chakri-pd** [octodns/octodns#424]
We have a usercase where dynamic records get create/delete through TF or ruby/python r53 api's when we provision and tear down the resources. In the same zone, we have some static records requests that come through from support where we are trying to streamline using octodns and git for version control. 
One way to achieve would be to take octodns-dump and make necessary changes push to git and sync. Still, we may see some dynamic records that may get-in in the meantime. So one thought would be something like 
`octodns-sync --config-file=./config/production.yaml --no-delete`

A flag that can override only the records that it finds in its <zone>.yaml and ignore the rest of the records.
any thoughts, please share.

**Comment by brianeclow** [comment]
The easiest way I found is to `octodns-dump` the record set down, then update with `excluded`. Or just create `excluded` records that match pattern. Something like:

```
---
? ''
: - octodns:
      excluded:
      - provider
    ttl: 60
    type: A
    values:
    - 192.168.1.2
    - 192.168.50.50
  - type: MX
    values:
    - exchange: mx.example.com.
      preference: 10
www:
  octodns:
    excluded:
    - provider
  type: CNAME
  value: magic.dynamic.endpoint.com.
```
