### ISSUE TITLE
ConfigProvider - source config dynamically

### ISSUE THREAD

**Issue by danhanks** [octodns/octodns#629]
I would be interested in the concept of a ConfigProvider. In a fashion similar to how sources and targets are pluggable, being able to write custom modules from which to fetch config data would be very useful (for example, if I wanted to manage the list of zones and their sources and targets in a database).

**Comment by ross** [comment]
Interesting. Seems like a useful/viable abstraction. I'd probably steer clear of calling it "provider" (and source) since that term is already claimed by the dns provider class hierarchy. 

Would have to think a bit about what would make sense there. I guess there'd still need to be a `--config-file` to set up the base level config and to configure the dynamic list of zones. I guess `YamlProvider` wouldn't make much sense in that sort of setup, but other existing sources/providers could, though that'll have interesting implications for things.

**Comment by yzguy** [comment]
Reminds me of LibreNMS generating Oxidized configuration: https://docs.librenms.org/Extensions/Oxidized/

**Comment by danhanks** [comment]
One way to approach this would be to default to using the current YAML-based config (for easy backward-compatibility), but also allowing specific directives in the 'base' config that would reference dynamic config sources. For example a 'base' YAML config could look like this:
```
---
dynamic_config:
  db_foo:
    class: octodns.dyn_config.db_foo.FooConfig
    param1: value1
    param2: env/ENV_VAR
  cloud_config:
    class: octodns.dyn_config.cloud_config.CloudConfig
    param1: value1
    param2: value2
    ...

providers:
  ...

zones:
  ...
```
So the look and feel of dynamic config sources would be very similar to providers. The dynamic config sources would return config info when called, and this config info could be merged into the 'base' config data.
