### ISSUE TITLE
Document unsafe threshold configuration

### ISSUE THREAD

**Issue by cs278** [octodns/octodns#638]
#120 added the ability to configure the unsafe percentage thresholds, but there is no documentation on how to change this. I had to blame the code to find the PR and found this helpful comment:

This PR should allow you to pass an update and/or delete threshold argument to the provider to override the default threshold of 30%. 

That would look something like:

```
  dyn:
    class: octodns.provider.dyn.DynProvider
    update_pcent_threshold: .4
    delete_pcent_threshold: .4
```

_Originally posted by @joewilliams in https://github.com/github/octodns/issues/120#issuecomment-335617349_
