### ISSUE TITLE
Unused pools error for fallback-only pools

### ISSUE THREAD

**Issue by viranch** [octodns/octodns#694]
I have a use-case to create a dynamic record with different fallback pools for each rule. Here's an example:

```yaml
example:
  ttl: 300
  type: A
  values: [4.4.4.4]
  dynamic:
    pools:
      one:
        fallback: two
        values:
          - value: 1.1.1.1
      two:
        values:
          - value: 2.2.2.2
      three:
        values:
          - value: 3.3.3.3
    rules:
      - geos:
        - NA-US
        pool: one
      - geos:
        - AS-SG
        pool: three
```

In other words, my default/fallback is different for each region. These fallbacks are not used as primary pool for any rule. This causes octoDNS to throw the 'unused pool' error. I'd like to skip this validation altogether. Having an unused pool doesn't seem all that practically harmful.

I looked at the code, and it seems pretty straight-forward to skip this validation. I can submit a PR but I wanted to open this issue to check what the authors think first.
