### ISSUE TITLE
Allow failover configuration in rules

### ISSUE THREAD

**Issue by viranch** [octodns/octodns#702]
I have a use-case for configuring a different failover path/order per region.

For example, I have local presence in LHR (UK), FRA (Germany) and IAD (US). I want UK to failover to FRA, while Germany should failover to LHR (both eventually failover to IAD). If I try to configure this in the pools, it will run into a failover loop. I could create copies of `lhr` and `fra` but that's a long workaround with same IPs in multiple pools, making any changes hard and error prone:

```yaml
  dynamic:
    pools:
      lhr-fra:
        fallback: fra
        values:
        - value: 1.1.1.1
      fra-lhr:
        fallback: lhr
        values:
        - value: 2.2.2.2
      lhr:
        fallback: iad
        values:
        - value: 1.1.1.1
      fra:
        fallback: iad
        values:
        - value: 2.2.2.2
      iad:
        values:
        - value: 3.3.3.3
    rules:
    - geos:
      - EU-UK
      pool: lhr-fra
    - geos:
      - EU-DE
      pool: fra-lhr
    - pool: iad
```

Instead, it will be much cleaner to be able to configure the failover in rules section, something like so:

```yaml
  dynamic:
    pools:
      lhr:
        values:
        - value: 1.1.1.1
      fra:
        values:
        - value: 2.2.2.2
      iad:
        values:
        - value: 3.3.3.3
    rules:
    - geos:
      - EU-UK
      pools: [lhr, fra, iad]
    - geos:
      - EU-DE
      pools: [fra, lhr, iad]
    - pool: iad
```

This is how its represented in Dyn anyway. NS1 can also be setup to do this. I'm not sure about Route53. Is it something octoDNS can add support for?
