### ISSUE TITLE
documentation for lenient in yaml config file seems to be wrong

### ISSUE THREAD

**Issue by shollingsworth** [octodns/octodns#707]
from https://github.com/octodns/octodns/blame/master/docs/records.md#L106

When I was doing a sync operation, the following configs worked / didn't work.

### Works:
```
zones:
  domain.com.:
    lenient: true
    sources:
    - route53
    targets:
    - yaml
```

### Does not work:
```
zones:
  domain.com.:
    octodns:
        lenient: true
    sources:
    - route53
    targets:
    - yaml
```
