### ISSUE TITLE
Allow the option to not pass Host header in healthchecks

### ISSUE THREAD

**Issue by meghashyamps** [octodns/octodns#710]
Currently, OctoDNS allows a "host" value to be set under the healthcheck block. This gets used as the Host header value as part of "String to send" field in NS1 TCP monitor. 

Sample zone file hc-zone.com.yaml
```
---
test:
  ...
  octodns:
    healthcheck:
      host: my-host-name
      path: /dns-health-check
      port: 443
      protocol: HTTPS
  ...
```

When this `host` value is not set it defaults to using `record.zone.` which is `test.hc-zone.com.`. This value is used across all the monitors created as part of a dynamic record, which means all the monitors created for all the answers inside a dynamic record will all have this host field in their TCP monitors. This will break the healthchecks in certain implementations where the server does not allow invalid domains in the host header value and returns a HTTP 400. Consider this example:

Sample zone file `hc-zone.com.yaml`
```
---
test:
  dynamic:
    pools:
      apac:
        values:
        - value: apac-test.com
      eu:
        values:
        - value: eu-test.com
    rules:
    - geos:
      - AS
      pool: apac
    - geos:
      - EU
      pool: eu
    - pool: eu
  ttl: 60
  type: CNAME
  values:
  - default-test.com
  octodns:
    healthcheck:
      host: my-host-name
      path: /dns-health-check
      port: 443
      protocol: HTTPS
```

The monitors created for `apac-test.com` and `eu-test.com` will both have `test.hc-zone.com.` as the host header value.
In this case `test.hc-zone.com.` is just a dynamic record to hand out either `eu-test.com` or `apac-test.com` both of which are genuine endpoints with valid certificates, but `test.hc-zone.com` is not.

Here is a sample of curls failing if invalid host header values are used:

```
$ curl https://www.facebook.com/ -H "Host:facebosdfwefdsfok.com" -I
HTTP/2 400
vary: Accept-Encoding
content-type: text/html; charset="utf-8"
x-fb-debug: Xd6rbQLZW+AdoKcNTCGZFz/TflvJa7FcBwpUygJu3MkBuN5Zn7WdZhG7RsBlu3pP0oDzriZR/VFEAhcvjxo/uQ==
date: Thu, 13 May 2021 18:33:33 GMT
alt-svc: h3-29=":443"; ma=3600,h3-27=":443"; ma=3600

```

Here are the ways to fix this issue:
1. Adding support to *not* send any value for host header, so internally the request will default to using the domain from the URL (or)
2. Adding support to override the host header value at the answer level, so the monitor for "apac-test.com" can set its host to "apac-test.com" (or)
3. Adding support for NS1's natively supported HTTP monitor
