### ISSUE TITLE
NS1: Creating notification list only if it does not exist

### ISSUE THREAD

**Issue by meghashyamps** [octodns/octodns#718]
Current implementation creates a notification list per record per answer as seen below:

![image](https://user-images.githubusercontent.com/13583698/118861705-a7357800-b891-11eb-9af7-b8d61f2cc3a2.png)

The notifiers in each of the notification lists are exactly the same, yet it ends up creating multiple of these lists instead of reusing a single list. 

One of the main use cases for us is having 2 or 3 main notification lists, something like so:
1. production_notification_list
2. test_notification_list
3. other_notification_list

and then reusing these 3 in relevant monitors. 

What do you think about creating a common notification list instead of per record per answer? (I can open a PR for this)

**Comment by ross** [comment]
Having the search my memory, it was a long while ago now and it's not something I've thought about since so I don't remember exactly why it is the way it is currently. 

Other than having a lot of them what downsides are there to having a list per item?

It'd be a fairly big change to the code, mostly in that it would have to preserve backwards compatibility with what's been created for existing uses. It would have to seamlessly switch things over and back (in case someone upgrades and then downgrades...)

Anyway, there are a few cases where this sort of change has been made, but it's only worth it when it's absolutely required, which isn't often.

**Comment by meghashyamps** [comment]
The main concern is the possibility of multiple repeated notifications of the same monitor (answer) event. Consider this:

We have many dynamic records in production, and some of them have same answers in some pools like so:
```
# excerpt from test.com.yaml

 www:
   dynamic:
     pools:
       pop1:
         values:
         - value: pop1-fqdn.test.com
```
and
```
# excerpt from www2.test.com.yaml

 www2:
   dynamic:
     pools:
       pop_rr:
         values:
         - value: pop1-fqdn.test.com
         - value: pop2-fqdn.test.com
```

Now, because of the way it is implemented currently, `pop1-fqdn.test.com` is going to be monitored by two different monitors. One as part of `www.test.com` and the other as part of `www2.test.com`. The current workflow also creates a unique `notify_list` for every monitor. So any status up/down event on `pop1-fqdn.test.com` is going to trigger notifications on two notification lists. And once https://github.com/octodns/octodns/issues/719 (I am working on it) is taken care of, it is going to trigger emails on two notification lists, there by getting 2 emails for the same endpoint status up/down event. And if an endpoint is used in N places, we are going to get N email notifications. 

Yes, this is going to be a big change. So I am going try and see if there is a way around it without having to implement this. 

Thank you
