### ISSUE TITLE
Support for adding email as one of the notifiers in the notification list / monitors

### ISSUE THREAD

**Issue by meghashyamps** [octodns/octodns#719]
Current workflow only allows `NSONE Data Feed (and hence NS1 datasource)` as a notifier for any notification list. 
![image](https://user-images.githubusercontent.com/13583698/118864249-a6521580-b894-11eb-9e58-f7a4e5beb482.png)

There are other notifiers available that can be added to a notification list. 
![image](https://user-images.githubusercontent.com/13583698/118863989-5f642000-b894-11eb-8fb2-7601d591afac.png)

It is very common to have an email alias as one of the notifiers, as in our production. 

What do you think about having an optional section under the monitor blob in the yaml that would contain details such as email etc? Something like this below (so it also gives the option of having a different email for different record if needed):

```
  ...
  octodns:
    healthcheck:
      host: my-host-name
      path: /dns-health-check
      port: 443
      protocol: HTTPS
      notify:
        email: test@abc.com
```

I believe AWS supports SNS email, and Azure as well through Azure Monitor.
