### ISSUE TITLE
Split Horizon in AWS

### ISSUE THREAD

**Issue by jeffadams** [octodns/octodns#728]
Route53 allows you to create private and public zones with the same name in the same account. The private is attached to a VPC, everyone else gets the public. It's a super useful feature, but the Route53 provider doesn't support it. The only way to get that behavior with Octodns is by hosting the zones in different AWS accounts. 

I know there have been previous discussions of this and there were proposed solutions. What about the option of explicitly pinning a target to a zone id, like this:

```
route53_public:
    class: octodns.provider.route53.Route53Provider
    access_key_id: env/AWS_ACCESS_KEY_ID
    secret_access_key: env/AWS_SECRET_ACCESS_KEY
    zone_id: env/ZONE_ID
```

That would be a compromise between using zone metadata to suss out what zone should be used and not supporting the feature at all. Just let the user choose but make it explicit.

**Comment by ross** [comment]
This is a duplicate of https://github.com/octodns/octodns/issues/190 & https://github.com/octodns/octodns/issues/420.

There was a WIP PR looking into this https://github.com/octodns/octodns/pull/421, but it hasn't resolved or shipped. Please track in the other issues.

**Comment by JohanLeirnes** [comment]
@ross both thoose are closed, is there any opened issue for this in the new repo.

**Comment by ross** [comment]
> is there any opened issue for this in the new repo.

Doesn't look like it. I guess it stalled out and was forgotten about. My gut says that the VPC-ID would be better tied to provider rather than per zone, that way you could do things like:

```yaml
providers:
  vpc-1234:
    ...

  vpc-2345:
    ....

zones:
  something.in.both.:
    sources:
      ..
    targets:
      - vpc-1234
      - vpc-2345
```

Don't off-hand know if that'll run into any problems. Working on `Route53Provider` is annoying as it costs me $ out of my own pocket, so if you have a TAM or any connections there i'd be nice if they could do something like a lot of the other providers and provide some sort of test account or credits.
