### ISSUE TITLE
Options to fix 64 char limit for notification lists

### ISSUE THREAD

**Issue by meghashyamps** [octodns/octodns#747]
```
www:
  dynamic:
    pools:
      eu:
        fallback: na
        values:
        - value: pop-europe-alpha.api.mydomain-bi.com.      <--- notify list name for this exceeds 64 chars
      na:
        values:
        - value: pop-beta.api.mydomain-bi.com.
        - value: pop-gamma.api.mydomain-bi.com.
    rules:
    - geos:
      - EU
      pool: eu
    - geos:
      - NA
      pool: na
    - pool: na
  octodns:
    healthcheck:
      host: null
      path: /pop/admin
      port: 443
      protocol: HTTPS
  ttl: 300
  type: CNAME
  value: pop-delta.api.mydomain-bi.com.
```

During migration to prod, we noticed that some of the answers were long and their notification list names were exceeding the 64 character limit that is set by NS1 (Octo prepends the answer with host and "CNAME" with spaces and dashes - to push it over 64 chars).  

```
ns1.rest.errors.ResourceException: server error: Input validation failed (Value u'www.sham-test2.com - CNAME - pop-europe-alpha.api.mydomain-bi.com' for field '<obj>.name' must have length less than or equal to 64)
```

First off, changing our answers to shorter FQDNs is not an option since the current FQDNs have some contextual meaning as to why they are the way they are.

Some options that could fix this:
1. Convert the names of all notification lists to its [md5sums](https://stackoverflow.com/a/5297483) before creating them, so their names will be their md5sums string
2. Convert only the ones whose name are > 64 chars to md5sum, where as the rest will follow along what is there currently
3. Have just one global notify list that **all** monitors use, since we are just creating identical notification lists anyway. Our earlier discussion touched on [this](https://github.com/octodns/octodns/issues/718) briefly. 
4. Any other option I have not thought about yet

We do not track notify lists today, nor do we parse its notes (or name) to get other info. So I believe that makes options 1 and 2 (may be even 3) both forward and backward compatible. 

Let me know which way is best, and I will work on getting a PR out.
