### ISSUE TITLE
Zone level "extra" config like default ttl

### ISSUE THREAD

**Issue by ross** [octodns/octodns#75]
Not 100% sure it'd make sense without looking into the details, but it'd be nice to avoid having to copy a common ttl across all/most of the records in a zone and the provider-level default isn't sufficient since it would apply to all zones and there are cases where different TTLs make sense.

**Comment by poblahblahblah** [comment]
We do something similar to this with YAML anchors:
```
---
'e': &CNAME_DEFAULTS
  ttl: 3600
  type: CNAME
  value: email.example.net.

'email':
  <<: *CNAME_DEFAULTS

'ftp':
  <<: *CNAME_DEFAULTS
  value: example.com.

'imap':
  <<: *CNAME_DEFAULTS
  value: example.net.
```

It would be much nicer if we could define some defaults at the top of the file:

```
---
__cname_defaults:
  ttl: 3600
  type: CNAME

# use the defaults
'e':
  value: example.com

# override the defaults
'f':
  ttl: 60
  value: example.com
```

**Comment by patcon** [comment]
Great call on yaml anchors, at least when same file. Hitting same issue where I wish to set default for octodns metadata like

```yml
- type: A
  value: 123.45.67.89
  octodns:
    cloudflare:
      proxied: true
```

Basically, wishing to set proxy to true be default, and only specify it when turning it off :) Thanks for considering!
