### ISSUE TITLE
The standalone validate command ignores `lenient` 

### ISSUE THREAD

**Issue by brianeclow** [octodns/octodns#772]
We have a non-root ALIAS entry which co-exists with another record type, as in this example:

```yaml
entry:
- octodns:
    lenient: true
  ttl: 3600
  type: ALIAS
  value: targetalias.example.com.
- type: TXT
  value: magictextvalue
```

This seems to be the only non-root ALIAS validate is taking issue with during the run. The sync command has no problem with this setup, which is why we didn't notice until a new project were we are, now, leveraging the validate command.
