### ISSUE TITLE
Support for NS1 healthcheck timeout options

### ISSUE THREAD

**Issue by bkane-msft** [octodns/octodns#805]
Some of our monitors use specific NS1 healthcheck options (converted from HTTP to TCP values due to octoDNS supporting HTTPS via TCP healthchecks:

- connect_timeout: "Timeout (in ms) before we give up trying to connect."
- response_timeout: "Timeout (in ms) after connecting to wait for output."

Right now these [are hardcoded](https://github.dev/octodns/octodns/blob/4305a75eaaf3519599fdb0cad039db720fcf2fca/octodns/provider/ns1.py#L1056). 

Would you accept a PR to add them to the `octodns` section of a dynamic record description, similar to [route53's options](https://github.com/octodns/octodns/blob/master/docs/dynamic_records.md#route53-healtch-check-options)?

Like:

```yaml
  octodns:
    healthcheck:
      host: my-host-name
      path: /dns-health-check
      port: 443
      protocol: HTTPS
    route53:
      healthcheck:
        measure_latency: false
        request_interval: 30
    ns1:  # THIS IS NEW
      healthcheck:
        connect_timeout: 3000 # in ms
        response_timeout: 3000 # in ms
```
