### ISSUE TITLE
Multiple NS records for a subdomain in a zone marked as duplicates

### ISSUE THREAD

**Issue by ammarzuberi** [octodns/octodns#861]
I'm trying to point a subdomain of a zone managed by OctoDNS at a different DNS server. For example, I'm adding records to my "root" domain like:

```
example:
  - value: laila.ns.cloudflare.com.
    ttl: 3600
    type: NS
  - value: memphis.ns.cloudflare.com.
    ttl: 3600
    type: NS
```

OctoDNS thinks these are duplicates and it doesn't look like this case is handled:
https://github.com/octodns/octodns/blob/e155ba9326884f1156efd9189000f99ee76c59d5/octodns/zone.py#L90

```
octodns.zone.DuplicateRecordException: Duplicate record example.mydomain.com., type NS
```

**Comment by viranch** [comment]
You want to use `values` instead of `value` and put a list of NS records in there.

```
example:
  - type: NS
    ttl: 3600
    values:
      - laila.ns.cloudflare.com
      - memphis.ns.cloudflare.com
```
