### ISSUE TITLE
Pass GitHub Actions secrets to OctoDNS

### ISSUE THREAD

**Issue by confis** [octodns/octodns#870]
Any idea how to use git secrets on the yaml file?

```yaml
cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    email: ${{ secrets.CLOUDFLARE_EMAIL }}
    token: ${{ secrets.CLOUDFLARE_TOKEN }}
```

**Comment by confis** [comment]
thank you for your suggestion - I tried it but it didn't work
same error 
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    email: $CLOUDFLARE_EMAIL
    token: $CLOUDFLARE_TOKEN  


the issue with YAML is the encryption of the secret (I think)

**Comment by yzguy** [comment]
In the YAML file you actually need just as I posted

```
cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    email: env/CLOUDFLARE_EMAIL
    token: env/CLOUDFLARE_TOKEN
```

[manager.py](https://github.com/octodns/octodns/blob/69e7632df3fe342846b8506c12411bb2356a1b8a/octodns/manager.py#L207-L214) is written to see when the config specifies `env/` and the go load from the environment variable specified after it.
