### ISSUE TITLE
Null MX records throw ValidationError

### ISSUE THREAD

**Issue by viranch** [octodns/octodns#879]
FQDN validation for MX records introduced in #873 has started causing `ValidationError`s on [null MX records](https://datatracker.ietf.org/doc/html/rfc7505).

```
octodns.record.ValidationError: Invalid record test.com.
  - Invalid MX exchange "." is not a valid FQDN.
```

Example null MX record:

```
'':
  - type: MX
    ttl: 86400
    values:
    - exchange: .
      preference: 0
```

RFC also notes that `.` is not a valid FQDN and should be considered a special case.
