### ISSUE TITLE
Unable to create same name, different type records

### ISSUE THREAD

**Issue by alexander-tachev** [octodns/octodns#888]
First, congratulations on the project, I do love it.

The problem is, (in use with Google Cloud DNS provider) when I try to create, let us say two records, named "test", one of type A and one of type TXT. Inside the yaml they look like that:

test:
  type: TXT
  values:
    - "Sample repeating record"

test:
  ttl: 60
  type: A
  values:
    - 192.168.0.23

octoDNS marks the first record to be deleted and creates the second one. The very first, coming to my mind is validating both the key and the type. Can you please implement it?

**Comment by brianeclow** [comment]
Combining them into a single stanza will avoid the create/delete issue:

```yaml
test:
  - type: TXT
     value: "Sample repeating record"
  - ttl: 60
     type: A
     value: 192.168.0.23
```
