### ISSUE TITLE
octodns-dump does not respect YamlProvider configuration

### ISSUE THREAD

**Issue by viranch** [octodns/octodns#897]
I prefer to not skip defaults (like TTL) in the yamls when dumping. So as a work-around, I set it to an odd unlikely number in the config, but I noticed octodns-dump command does not really respect the provider config:

```yaml
providers:
  cfg:
    class: octodns.provider.yaml.YamlProvider
    directory: ./src/dev/test
    default_ttl: 9
    enforce_order: False
```

I think this line here doesn't take any provider configs into account https://github.com/octodns/octodns/blob/master/octodns/manager.py#L570.

May be we add the ability to set these provider configs as CLI switches since there can be multiple YamlProvider configs in the config file and dump would not know which one to pick. Or provide one switch to disable omitting default values.

**Comment by ross** [comment]
Yeah, issue here is that it creates a `YamlProvider` on the fly to do the dump and there's no way to configure the details of it.

Quick work-around would be to do

```yaml
zones:
  whatever.com.:
      sources:
      - something
      targets:
      - config
```

Broader solution will probably involve improving dump so that it can use a configured provider, quick thoughts on that:
- it could allow you to specify a provider id/name and then verify that it's a YamlProvider and use it
- `--output-dir` could still specify where the dump goes to, but we'd probably need to duplicate the provider before changing its `output_dir`
- it could potentially search for a YamProvider to use, but that seems a bit dangerous in terms of accidentially overwriting files without any directive to do so
