### ISSUE TITLE
one record different values per provider

### ISSUE THREAD

**Issue by hijak** [octodns/octodns#899]
hi 

im trying to achieve something like this inside the zone file

```
test1: 
  - octodns:
      included:
        - powerdns-1
        - powerdns-2
    ttl: 1
    type: TXT
    value: 'record for 1 and 2'
  - octodns:
      included:
        - powerdns-3
    ttl: 1
    type: TXT
    value: 'record for 3'
```

but octo complains that this is a duplicate record. is there any way around this?

**Comment by ross** [comment]
There's no way to have two records with the same type and name coexist in the same zone so that's not directly possible. It's just not a use case that things were designed for. The best way I can think of to accomplish that setup is to have multiple yaml providers and configs, something like:

### config/whatever.com.yaml

```yaml
---
# shared stuff

### config-1-and-2/whatever.com.yaml

```yaml
---
# records for 1 & 2
test1:
    ttl: 1
    type: TXT
    value: 'record for 1 and 2'
```

### config-3/whatever.com.yaml

```yaml
---
test1:
    ttl: 1
    type: TXT
    value: 'record for 1 and 2'
```

And then set up the octodns config's something like:

### config-1-and-2/production.yaml

```yaml
providers:
  config:
    directory: ./config

  config-1-and-2:
    directory: ./config-1-and-2

   provider-1:
...
   provider-2:
...

zones:
  whatever.com.:
    sources:
      - config
    targets:
      - provider1
      - provider2
```

### config-3/production.yaml


```yaml
providers:
  config:
    directory: ./config

  config-3:
    directory: ./config/config-3
    populate_should_replace: true

   provider-3:
...

zones:
  whatever.com.:
    sources:
      - config
      - config-3
    targets:
      - provider-3
```

I'll think about it a bit more and see if I can come up with anything else, but nothing is immediately popping into mind.

**Comment by ross** [comment]
So I don't know that this is "better" but it's a little less convoluted...

You could create a custom provider that inherits from `PowerDnsProvider`, e.g.

```python
class OverridingPowerDnsProvider(PowerDnsProvider):

    def _process_desired_zone(self, desired):
        our_id = self.id

        for record in desired.records:
            if 'target-overrides' in record._octodns:
                overrides = record._octodns['target-overrides']
                values = overrides.get(our_id)
                if not isinstance(values, list):
                    values = [values]
                if values != record.values:
                    record = record.copy()
                    record.values = values
                    desired.add_record(record, replace=True)

        return super()._process_desired_zone(desired)
```

And then use it in place of `octodns_powerdns.PowerDnsProvider` in your configs. That would allow you to do something like the following in the zone yaml file:

```yaml
---
test1:
    octodns:
      target-overrides:
        powerdns-3: 'record for 3'
    ttl: 1
    type: TXT
    value: 'record for 1 and 2'
```
