### ISSUE TITLE
Leveraging TypeRejectlistFilter Processor

### ISSUE THREAD

**Issue by brianeclow** [octodns/octodns#900]
NS1's new `NS1 Connect platform` has a major API difference in how they handle outputting zone information in regards to `URLFWD`s. This has put a full stop to leveraging octoDNS on any zone with a `URLFWD` in it. They are currently evaluating how to fix the issue. However, in the mean time, we need a work around.

It appears the `TypeRejectlistFilter` processor would be the solution, however, I cannot seem to have it engage on ignoring the `URLFWD` type. Based on issue #367, the following should work.

Config:

```yaml
processors:
  nourlfwd:
    class: octodns.processor.filter.TypeRejectlistFilter
    rejectlist:
      - URLFWD
providers:
  data:
    class: octodns.provider.yaml.YamlProvider
    directory: ./data
  nsone:
    api_key: env/NS1_API_KEY
    class: octodns_ns1.Ns1Provider
```

Zone:

```yaml
zones:
  example.com.:
    processors:
    - nourlfwd
    sources:
    - data
    targets:
    - nsone
```
