### ISSUE TITLE
ZoneFileSource provider to support multi-valued PTR records?

### ISSUE THREAD

**Issue by harpreetnav** [octodns/octodns#912]
I'm going through the process of importing our zone file into yaml.  some of our PTR records have multiple values, however these are not handled by the `ZoneFileSource` provider. any chance that this could be supported?

eg:

in `10.in-addr.arpa.dns`
```txt
1.2.3  PTR name1.domain1.abc.
          PTR name2.domain2.xyz.

```

currently run this through the `ZoneFileSource` provider will only yield the following

```yaml
1.2.3:
  ttl: 18000
  type: PTR
  value: name1.domain1.abc.
```

any chance of having the support to capture both PTR values from the original zone file? esp now that octoDNS does support multi-valued PTR records? 

something like this

```yaml
1.2.3:
  ttl: 18000
  type: PTR
  values:
    - name1.domain1.abc.
    - name2.domain2.xyz.

```

or there's another method that i m not aware of?
