### ISSUE TITLE
Best way to share multiple records between zones

### ISSUE THREAD

**Issue by felixoi** [octodns/octodns#962]
I'd like to share a couple of records between multiple zones. For example I'm using the same autodiscover/autoconfig records for multiple domains:
```
_autodiscover._tcp:
  type: SRV
  value:
    priority: 10
    weight: 10
    port: 443
    target: autodiscover.mailcow.de.

_autoconfig._tcp:
  type: SRV
  value:
    priority: 10
    weight: 10
    port: 443
    target: autoconfig.mailcow.de.

autodiscover:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: autodiscover.mailcow.de.

autoconfig:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: autoconfig.mailcow.de.
```
As the other records differ I cannot use the "alias" functionality for zones. What's the best way to achieve shared records in octodns? I don't like to copy & paste in "as code" approaches. An option would maybe be an separate yaml templating preprocessor, as I would guess that I'm not the only one sharing records between zones, it does not seem to be the perfect approach to me tho. A YAML provider which just returns the same records for every zone would maybe work? Is there something prebuild like this?

**Comment by ross** [comment]
Not what you're asking for, but [Yaml anchors](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/) are useful for avoiding repeating the same bits of yaml within a single zone, e.g.:

```yaml
_autodiscover._tcp: &auto
  type: SRV
  value: 
    priority: 10
    weight: 10
    port: 443
    target: autodiscover.mailcow.de.

_autoconfig._tcp: *auto
```

As for records shared across zones YAML itself doesn't support any sort of `!include` directive so there's no inbuilt way to do what you're after.  I've wanted it in the past as well and have kicked around ideas for ways to support it, but haven't come up with anything viable. 

I just had a new thought about something that might make it possible that I'll play around with in the next few days to see if it's workable. Will report back what I find.

**Comment by felixoi** [comment]
Yeah I'm aware of anchors but as you mentioned they do not fit my usecase. I look forward to your feedback on whether it works.

**Comment by ross** [comment]
So my first thought wasn't viable. I was looking into adding a parameter to `YamlProvider` that allowed you to define a "shared" bit of yaml that was prepended onto the zone file before parsing. That runs into problems with files starting with `---` and beyond that sorting/ordering issues. 

Still have one more thing in mind...

**Comment by ross** [comment]
> Still have one more thing in mind...

Scratch that, forgot that anchors always have to come before their usage.

**Comment by felixoi** [comment]
Why wouldn't a completely new provider (e.g. SharedYAMLProvider) which takes a file instead of a directory and also a populate_should_replace argument not work? As every other provider if you add it to your zone in the config, it will add the records. The provider is just not based on any zone argument, instead it just everytime adds the same records defined in the file to every zone where it's added as source. This is just a quick ideas without a deep code knowledge

**Comment by ross** [comment]
See https://github.com/octodns/octodns/pull/961 for something related to that path:

It could be hacked in as-is, but it doesn't support using anchors across the shared and zone files, something that would be extra useful/powerful as it'd let you define non-trivial "values" and then apply them across different records in different zones.

octoDNS's YamlProvider will already support shared records that are added to multiple zones w/o any anchor sharing. That's something I've done in the past. Something like:

```yaml
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config

  shared:
    class: octodns.provider.yaml.YamlProvider
    directory: ./shared

zones:
  example.com.:
    sources:
      - config
      - shared
    targets:
      ...

  example.org.:
    sources:
      - config
      - shared
    targets:
      ...
```

Then you could have a `config` directory with files named for the zones that hold the zone specific records and a `shared` directory with a single yaml file in it, `shared.yaml` and then symlink all the zone files that used `shared` to it. That gives you full control over the order in which things are read and whether or not duplicates are replaced or throw errors. It also allows you to add other providers into the mix at appropriate points.
